# -*- coding: utf-8 -*-
"""Day 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/153cO282BHLdfo21W41lnG9RH7Abgh9C1

# **CHALLENGE DAY 6**

# Task 1

Create a program that reads two integers, a and b, from the user. Your program should
compute and display:

1. The sum of a and b
2. The difference when b is subtracted from a
3. The product of a and b
4. The quotient when a is divided by b
5. The remainder when a is divided by b
6. The result of log10 a
7. The result of a^b
"""

#importing math library for the log10 task
from math import log10

#asking user to enter input and using try/except to prevent program from crashing if user enters a non-number
try:
  a = int(input("Please enter any number: "))
  b = int(input("Please enter another number: "))

#defining stipulated arithmetric tasks
  task1 = a + b
  task2 = a - b
  task3 = a * b
  task4 = a / b
  task5 = a % b
  task6 = log10(a)
  task7 = a ** b

#printing output
  print("\n")
  print("Sum =", task1,"; Difference(a-b) =", task2,"; Product =", task3,"; Quotient(a/b) =",\
      task4,"; Remainder(a/b) =", task5,"; Log10(a) =", round(task6,2),"; Exponent(a^b) =", task7)

#output to print if an invalid input is entered
except ValueError:
  print("Please enter a valid input")

"""# Task 2

In this exercise you will create a program that computes the average of a collection of values entered by the user. The user will enter 0 as a sentinel value to indicate that no further values will be provided. Your program should display an appropriate error message if the first value entered by the user is 0.
"""

#importing mean function from the statistics library
from statistics import mean

#asking user to enter input and using try/except to prevent program from crashing if user enters a non-number
try:
  user_num = int(input("Enter as much numbers as you wish here (enter 0 to finish): ")) #initialising the entry program

  if user_num == 0: #defining condition to rule out 0
    print("Your first number cannot be 0, please enter another valid number")
  else:

    total = []    #initialising the list to contain all values

    #stating condition to accept numbers into list
    while user_num != 0:
      total.append(user_num) #adding each new entry to list
      average = mean(total)  #calculating average using mean function
      user_num = int(input("Enter as much numbers as you wish here (enter 0 to finish): "))  #re-starting the program since the entry isn't 0
    print("The average of all numbers is {:.2f}".format(average))    #prints output

#output to print if an invalid input is entered
except ValueError:
  print("please enter a vaild input")