# -*- coding: utf-8 -*-
"""Day 11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BVxSrlHONXDksL1jEd8X3hzZmQ_QrirS

# **CHALLENGE DAY 11**

# Task 1

Many people think about their height in feet and inches, even in some countries that primarily use the metric system.

Write a program that reads a number of feet from the user, followed by a number of inches.

Once these values are read, your program should compute and display the equivalent number of centimeters.

Hint: One foot is 12 inches. One inch is 2.54 centimeters.
"""

#calling user to enter height in feet and inches
#and using try/except to prevent program from crashing if user keys a wrong input
try:
  user_height_feet = int(input("Please enter the 'feet' component of your height: "))
  user_height_inch = int(input("Please enter the inch component of your height: "))

  #defining formula for computing the centimeters equivalence of feet and inches
  height_centimeters = (user_height_feet * 12 * 2.54) + (2.54 * user_height_inch)

  #printing output
  print("You have entered your height as {}ft {}in, the equivalence in centimeters is {}cm.".\
        format(user_height_feet, user_height_inch, height_centimeters))

except:
  print("Please enter a valid input")

"""# Task 2

Write a function that determines how many days there are in a particular month. Your function will take two parameters: The month as an integer between 1 and 12, and the year as a four digit integer.

Ensure that your function reports the correct number of days in February for leap years.

Include a main program that reads a month and year from the user and displays the number of days in that month.
"""

#defining lists for months with respective numbers of days
months_with_31_days = [1, 3, 5, 7, 8, 10, 12]
months_with_30_days = [4, 6, 9, 11]

#using try/except to prevent program from crashing if user keys a wrong input
try:
  month = int(input("Please enter the month as a number only: "))   #calling user to enter month
  if month not in range(1,13):                                      #filtering out numbers that are out of month bound
    print("Please enter a valid month number")
  else:
    year = int(input("Please enter the year as a number only: "))   #calling user to enter year
    if len(str(year)) != 4:                                         #filtering out year entries that are not up to four digits
      print("Please enter a valid four digit year")
    else:

      def user(month, year):                                        #defining function
        if year % 4 == 0:                                           #conditions for a leap year
          if month in months_with_31_days:
            return "The number of days in this month is 31"
          elif month in months_with_30_days:
            return "The number of days in this month is 30"
          else:
            return "The number of days in this month is 29"
        else:                                                       #conditions for a non-leap year
          if month in months_with_31_days:
            return "The number of days in this month is 31"
          elif month in months_with_30_days:
            return "The number of days in this month is 30"
          else:
            return "The number of days in this month is 28"
      print(user(month, year))                                     #printing output

except ValueError:
  print("Please enter a valid input")