# -*- coding: utf-8 -*-
"""Day 14

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YGj-YYt18HaTSs05EaNnfT4NaaCTcGAy

# **CHALLENGE DAY 14**
"""

"""
In this exercise you will create a program that reads a letter of the alphabet from the user.
If the user enters a, e, i, o or u then your program should display a message indicating that the entered letter is a vowel.
If the user enters y then your program should display a message indicating that sometimes y is a vowel, and sometimes y is a consonant.
Otherwise your program should display a message indicating that the letter is a consonant.
"""

import string

user_entry = input("Please enter only one alphabet: ").lower()

alphabet_list = list(string.ascii_lowercase)

if user_entry not in alphabet_list:
  print("Please enter a valid single alphabet")
else:
  if user_entry == alphabet_list[-2]:
    print("Sometimes y is a vowel, and sometimes y is a consonant")
  elif user_entry == alphabet_list[0] or\
  user_entry == alphabet_list[4] or\
  user_entry == alphabet_list[8] or\
  user_entry == alphabet_list[14] or\
  user_entry == alphabet_list[20]:
    print("This is a vowel")
  else:
    print("This is a consonant")