# -*- coding: utf-8 -*-
"""Day 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fA8zqLrDJqdbQxWhmQxmKqOp7sWN_mJe

# **CHALLENGE DAY 5**

# Task 1

The program that you create for this exercise will begin by reading the cost of a meal ordered at a restaurant from the user.

Then your program will compute the tax and tip for the meal. Use your local tax rate when computing the amount of tax owing.


Compute the tip as 18 percent of the meal amount (without the tax). The output from your program should include the tax amount, the tip amount, and the grand total for the meal including both the tax and the tip.

Format the output so that all of the values are displayed using two decimal places.
"""

try: #using try to prevent the program from crashing
  meal_cost = float(input("Please enter the cost of your meal: "))  #calling user to input their meal cost
except:
  print("Please enter a valid input")

#defining formulas as instructed
tax = 0.05 * meal_cost
tip = 0.18 * meal_cost
grand_total = meal_cost + tax + tip

#printing output
print("The grand total of your meal is ${:.2f}, this includes tax of ${:.2f} and tip of ${:.2f}."\
      .format(grand_total, tax, tip))

"""# Task 2

The horoscopes commonly reported in newspapers use the position of the sun at the time of one’s birth to try and predict the future.

This system of astrology divides the year into twelve zodiac signs, as outline in the table below:


> **ZODIAC SIGN** ⏭⏭⏭⏭⏭ **DATE RANGE**

> Capricorn ⏭⏭⏭⏭⏭ December 22 to January 19

> Aquarius ⏭⏭⏭⏭⏭⏭ January 20 to February 18

> Pisces ⏭⏭⏭⏭⏭⏭⏭ February 19 to March 20

> Aries ⏭⏭⏭⏭⏭⏭⏭ March 21 to April 19

> Taurus ⏭⏭⏭⏭⏭⏭⏭ April 20 to May 20

> Gemini ⏭⏭⏭⏭⏭⏭⏭ May 21 to June 20

> Cancer ⏭⏭⏭⏭⏭⏭⏭ June 21 to July 22

> Leo ⏭⏭⏭⏭⏭⏭⏭⏭ July 23 to August 22

> Virgo ⏭⏭⏭⏭⏭⏭⏭ August 23 to September 22

> Libra ⏭⏭⏭⏭⏭⏭⏭ September 23 to October 22

> Scorpio ⏭⏭⏭⏭⏭⏭ October 23 to November 21

> Sagittarius ⏭⏭⏭⏭⏭ November 22 to December 21

Write a program that asks the user to enter his or her month and day of birth. Then your program should report the user’s zodiac sign as part of an appropriate output message.
"""

try: #using try to prevent program from crashing if wrong input is entered
  month = int(input("Please enter your month of birth as a number: "))  #user to enter month
  if month not in range(1,13): #ensuring valid month range is entered)
    print("Please enter a valid month number")
  else:
    date = int(input("Please enter your date of birth: "))  #user to enter date
except:
  print("Please enter a valid input")


def main():
  if month == 1:                              #defining zodiac signs for January and filtering out inavlid dates
    if date in range(1,20):
      print("Capricon")
    elif date in range(20,32):
      print("Aquarius")
    else:
      print("please enter a valid date")
  elif month == 2:                            #defining zodiac signs for February and filtering out inavlid dates
    if date in range(1,19):
      print("Aquarius")
    elif date in range(19,30):
      print("Pisces")
    else:
      print("Please enter a valid date")
  elif month == 3:                            #defining zodiac signs for March and filtering out inavlid dates
    if date in range(1,21):
      print("Pisces")
    elif date in range(21,32):
      print("Aries")
    else:
      print("Please enter a valid date")
  elif month == 4:                            #defining zodiac signs for April and filtering out inavlid dates
    if date in range(1,20):
      print("Aries")
    elif date in range(20,31):
      print("Taurus")
    else:
      print("Please enter a valid date")
  elif month == 5:                            #defining zodiac signs for May and filtering out inavlid dates
    if date in range(1,21):
      print("Taurus")
    elif date in range(21,32):
      print("Gemini")
    else:
      print("Please enter a valid date")
  elif month == 6:                            #defining zodiac signs for June and filtering out inavlid dates
    if date in range(1,21):
      print("Gemini")
    elif date in range(21,31):
      print("Cancer")
    else:
      print("Please enter a valid date")
  elif month == 7:                            #defining zodiac signs for July and filtering out inavlid dates
    if date in range(1,23):
      print("Cancer")
    elif date in range(23,32):
      print("Leo")
    else:
      print("Please enter a valid date")
  elif month == 8:                            #defining zodiac signs for August and filtering out inavlid dates
    if date in range(1,23):
      print("Leo")
    elif date in range(23,32):
      print("Virgo")
    else:
      print("Please enter a valid date")
  elif month == 9:                           #defining zodiac signs for September and filtering out inavlid dates
    if date in range(1,23):
      print("Virgo")
    elif date in range(23,31):
      print("Libra")
    else:
      print("Please enter a valid date")
  elif month == 10:                           #defining zodiac signs for October and filtering out inavlid dates
    if date in range(1,23):
      print("Libra")
    elif date in range(23,32):
      print("Scorpio")
    else:
      print("Please enter a valid date")
  elif month == 11:                           #defining zodiac signs for November and filtering out inavlid dates
    if date in range(1,22):
      print("Scorpio")
    elif date in range(22,31):
      print("Sagittarius")
    else:
      print("Please enter a valid date")
  else:                                      #defining zodiac signs for December and filtering out inavlid dates
    if date in range(1,22):
      print("Sagittarius")
    elif date in range(22,32):
      print("Capricorn")
    elif date not in (1,32):
      print("Please enter a valid date")

main()