# -*- coding: utf-8 -*-
"""Day 25

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KMbGm814j0TH1exa74kYkJljbWPkt75H
"""

"""
TASK 1
Create a program that determines how quickly an object is traveling when it hits the
ground. The user will enter the height from which the object is dropped in meters (m).
Because the object is dropped its initial speed is 0m/s. Assume that the acceleration
due to gravity is 9.8m/s2. You can use the formula (see diagram) to compute the
final speed, vf , when the initial speed, vi, acceleration, a, and distance, d, are known.
"""

from math import sqrt

height = float(input("Enter the height from which the object was dropped: "))

#formula:
#final speed = square root of (initial speed^2 + 2ad)

#assuming initial speed of 0 and acceleration of 9.8m/s2
final_speed = sqrt(2*9.8*height)

#printing output
print(f"\n{final_speed:.2f}m/s")

"""
TASK 2
In this exercise you will write a function named isInteger that determines
whether or not the characters in a string represent a valid integer. When determining
if a string represents an integer you should ignore any leading or trailing white space.
Once this white space is ignored, a string represents an integer if its length is at least
1 and it only contains digits, or if its first character is either + or - and the first
character is followed by one or more characters, all of which are digits.
Write a main program that reads a string from the user and reports whether or
not it represents an integer. Ensure that the main program will not run if the file
containing your solution is imported into another program.
"""

#defining function to determine an integer
def isInteger(entry):
  #ensuring that integers with symbols are accommodated
  if entry[0] == "+" or entry[0] == "-" or entry[0].isnumeric():
    
    if entry.isnumeric():   #integers without any preceding symbols
      return "Yes, it is an integer"
    elif entry[1:].isnumeric():   #integers with preceding symbols
      return "Yes, it is an integer"
    else:   #non-integers
      return "No, it is not an integer"

#defining main function and printing output afterwards
def main():
  entry = input("Enter a value: ").strip()
  print(isInteger(entry))
if __name__ == "__main__":
  main()
