# -*- coding: utf-8 -*-
"""Day 20

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pBDkarIm5NlBNjX25GMpYv2Xtbz186m7

# **CHALLENGE DAY 20**



# Task 1
"""

"""
Pretend that you have just opened a new savings account that earns 4 percent interest
per year. The interest that you earn is paid at the end of the year, and is added
to the balance of the savings account. Write a program that begins by reading the
amount of money deposited into the account from the user. Then your program should
compute and display the amount in the savings account after 1, 2, and 3 years. Display
each amount so that it is rounded to 2 decimal places.
"""

#using try/except to prevent the program from crashing
try:
  #inputting user's savings
  user = float(input("Please enter the amount of money you want to deposit: "))

  #interest rate
  interest_rate = 0.04

  #cumulative savings for each of the first three years
  one_year = user + (user * interest_rate)
  two_years = one_year + (one_year * interest_rate)
  three_years = two_years + (two_years * interest_rate)

  #output
  print(f"\nYou have entered {user} for your savings, with an interest rate of 4%, your earnings after 1, 2, or 3 years are below:\n")
  print(f"One year: {one_year:.2f}\n")
  print(f"Two years: {two_years:.2f}\n")
  print(f"Three years: {three_years:.2f}")

except ValueError:
  print("Please enter a numerical value.")



"""# Task 2"""

"""
A string is a palindrome if it is identical forward and backward. For example “anna”,
“civic”, “level” and “hannah” are all examples of palindromic words.
Write a program that reads a string from the user and uses a loop
to determines whether or not it is a palindrome.
Display the result, including a meaningful output message.
"""

#entering any word to test if it's a palindrome or not
word = input("Enter a word: ").strip().lower()

#converting the word to a list
word_list = list(word)

#reversing the elements of the list
reverse_word_list = word_list.reverse()

#initiating the reversed word
reverse_word = ""

#joining the elements in the reversed list
for ele in word_list:
  reverse_word += ele

#testing if the word is a palindromw or not
#and printing the corresponding output
if word == reverse_word:
  print(f"\n{word} is a palindrome.")
else:
  print(f"\n{word} is not a palindrome.")
