# -*- coding: utf-8 -*-
"""Day 31

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BOuliRlyKnRwEvin9R9GHcnr5s6_l8G4
"""

"""
A prime number is an integer greater than 1 that is only divisible by one and itself.
Write a function that determines whether or not its parameter is prime, returning
True if it is, and False otherwise. Write a main program that reads an integer
from the user and displays a message indicating whether or not it is prime. Ensure
that the main program will not run if the file containing your solution is imported
into another program.
"""

#defining function to determine prime number
def prime(user_num):
  
  #filtering out numbers less than or equal to 1, based ont the instruction's specifications
  if user_num <= 1:
    return False

  #for valid entries
  else:

    #excluding 1 and the number itself, and checking if there is any other number within its lower range
    #that can completely divide it, making it not to be a prime number
    #if there is not, then the entry is a prime number
    for num in range (2,user_num):
      if user_num % num == 0:
        return False
      else:
        return True

#defining main function
def main():

  #using try/except to prevent program from crashing
  try:
    #calling user to enter integer
    user_num = int(input("Enter an integer: "))

    #print output for prime numbers
    if prime(user_num):
      print(f"\n{user_num} is a prime number.")

    #print output for non-prime numbers
    else:
      print(f"\n{user_num} is not a prime number.")
  
  #error message for non-numeric entries
  except:
    print("Please enter a valid numeric input")

if __name__ == "__main__":
  main()