# -*- coding: utf-8 -*-
"""Day 34

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PtLIbvQNLrXfaRXB2979Rw418pqnQuKs
"""

"""
The year is divided into four seasons: spring, summer, fall and winter. While the
exact dates that the seasons change vary a little bit from year to year because of the
way that the calendar is constructed, we will use the following dates for this exercise:

SEASON    |   FIRST DAY
Spring    |   March 20
Summer    |   June 21
Fall      |   September 22
Winter    |   December 21

Create a program that reads a month and day from the user. The user will enter
the name of the month as a string, followed by the day within the month as an
integer. Then your program should display the season associated with the date that
was entered.
"""
#using try/except to prevent program from crashing if a non-numeric input is entered in date below
try:

  #calling user to enter month and date
  month = input("Enter the month: ").title().strip()
  date = int(input("Enter the date: "))

  #using complex conditionals to specify date conditions for each of the seasons
  #conditionals were created to accommodate only valid dates including leap year
  if (month == "January" and (date >= 1 and date <= 31)) or\
      (month == "February" and (date >= 1 and date <= 29)) or\
      (month == "March" and (date >= 1 and date <= 19)) or\
      month == "December" and (date >= 21 and date <= 31):
    print("Winter")

  elif (month == "March" and (date >= 20 and date <= 31)) or\
      (month == "April" and (date >= 1 and date <= 30)) or\
      (month == "May" and (date >= 1 and date <= 31)) or\
      (month == "June" and (date >= 1 and date <= 20)):
    print("Spring")

  elif (month == "June" and (date >= 21 and date <= 30)) or\
      (month == "July" and (date >= 1 and date <= 31)) or\
      (month == "August" and (date >= 1 and date >= 31)) or\
      (month == "September" and (date >= 1 and date <= 21)):
    print("Summer")

  elif (month == "September" and (date >= 22 and date <= 30)) or\
        (month == "October" and (date >= 1 and date <= 31)) or\
        (month == "November" and (date >= 1 and date <= 30)) or\
        (month == "December" and (date >1 and date <= 20)):
    print("Fall")

  #message for non-valid of months or dates
  else:
    print("Please enter a valid date and month")

#error message
except:
  print("Enter a valid date as a number")