# -*- coding: utf-8 -*-
"""Day 23

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11mGL9nG8mALyCcVmW5_9UvKTFY4V3_iK

# **CHALLENGE DAY 23**
"""

"""
The surface of the Earth is curved, and the distance between degrees of longitude
varies with latitude. 

As a result, finding the distance between two points on the surface
of the Earth is more complicated than simply using the Pythagorean theorem.

Let (t1, g1) and (t2, g2) be the latitude and longitude of two points on the Earth’s surface.
The distance between these points, following the surface of the Earth, in kilometers is:
distance = 6371.01 × arccos(sin(t1) × sin(t2) + cos(t1) × cos(t2) × cos(g1 − g2))

The value 6371.01 in the previous equation wasn’t selected at random. It is
the average radius of the Earth in kilometers.

Create a program that allows the user to enter the latitude and longitude of two
points on the Earth in degrees. Your program should display the distance between
the points, following the surface of the earth, in kilometers.

Hint: Python’s trigonometric functions operate in radians. As a result, you will
need to convert the user’s input from degrees to radians before computing the
distance with the formula discussed previously. The math module contains a
function named radians which converts from degrees to radians.
"""

#importing math module for the trignometric functions and for converting degrees to radians
import math

#using try/except to prevent program from crashing
try:

  #asking user to enter the coordinates of the points
  t1 = (float(input("Enter the latitude of point 1: ")))
  g1 = (float(input("Enter the longitude of point 1: ")))
  t2 = (float(input("Enter the latitude of point 1: ")))
  g2 = (float(input("Enter the longitude of point 2: ")))

  #formula for caluclating distance
  distance = 6371.01 * math.acos(math.sin(math.radians(t1)) * math.sin(math.radians(t2)) \
                               + math.cos(math.radians(t1)) * math.cos(math.radians(t2)) \
                               * math.cos(math.radians(g1)-math.radians(g2)))

  #printing output
  print(f"\nThe distance between two points ({t1}, {g1}) and ({t2}, {g2}) is:")
  print(f"{distance:.2f} kilometres")

except ValueError as err:
  print(f"\nYou have entered a wrong input, {err}, please enter a valid point")