# -*- coding: utf-8 -*-
"""Day 26

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cVs0os4unV7gK_aQW9-SyK86CzvO4JSd
"""

"""
Create a program that reads integers from the user until a blank line is entered. Once
all of the integers have been read your program should display all of the negative
numbers, followed by all of the zeros, followed by all of the positive numbers. Within
each group the numbers should be displayed in the same order that they were entered
by the user. For example, if the user enters the values 3, -4, 1, 0, -1, 0, and -2 then
your program should output the values -4, -1, -2, 0, 0, 3, and 1. Your program
should display each value on its own line.
"""

#asking user to enter the first value
entry = input("Enter a number (hit enter button to end): ").strip()

#initiating all lists
negatives = []
zeros = []
positives = []


while entry != "":
    #ensuring that integers with symbols are accommodated
  if entry[0] == "+" or entry[0] == "-" or entry[0].isnumeric() or entry[0] == "0":
    
    if entry.isnumeric():   #integers without any preceding symbols
      if entry[0] == "0":
        zeros.append(entry)
      else:
        positives.append(entry)

    elif entry[1:].isnumeric():   #integers with preceding symbols
      if entry[0] == "+":
        positives.append(entry)
      elif entry[0] == "-":
        negatives.append(entry)
    
  entry = input("Enter a number (hit enter button to end): ").strip()

#printing output
print("\nnegatives: ", negatives)
print("positives: ", positives)
print("zeros: ", zeros)